apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::793770371113:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-aYb6Eo7E8k2w
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-17T19:52:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1217"
  uid: 774ba1c9-a3da-4b37-b920-5873f1fb1238