apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::793770371113:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-aYb6Eo7E8k2w
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::793770371113:user/keke
      username: keke
    - groups:
      - roboshop-admin-access-all-v1-g
      - roboshop-admin-access-clusterlevel-pv-g
      userarn: arn:aws:iam::793770371113:user/anurag
      username: anurag
    
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system